name: vue-proj-service

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - "develop" # develop 브랜치에 푸시될 때 실행
  pull_request:
    types:
      - closed # PR이 병합될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Create .env File
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env
          echo "VITE_APP_TITLE=${{ secrets.VITE_APP_TITLE }}" >> .env
          echo "VITE_STATIC_FILES=${{ secrets.VITE_STATIC_FILES }}" >> .env

      - name: Build Vue Project
        run: npm run build

      - name: Notify Discord
        run: |
          # PR 제목 또는 커밋 메시지 가져오기
          if [ -n "${{ github.event.pull_request.title }}" ]; then
            PR_TITLE="${{ github.event.pull_request.title }}"
          else
            PR_TITLE="${{ github.event.head_commit.message }}"
          fi

          # JSON-safe 포맷으로 변환
          SAFE_PR_TITLE=$(echo "$PR_TITLE" | jq -R .)

          # 기본값 설정
          DURATION=${DURATION:-"알 수 없음"}
          ACTIONS_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Discord Webhook 호출
          send_discord_notification() {
            local status="$1"
            local title=""
            local color=""
            local description=""

            if [ "$status" = "success" ]; then
              title="✅ 빌드 성공 알림"
              color=3066993
              description="빌드가 성공했어핑! 🎉\\n\\n"
            else
              title="❌ 빌드 실패 알림"
              color=15158332
              description="빌드가 실패했어핑. 😢\\n\\n"
            fi

            curl -H "Content-Type: application/json" \
              -d "{
                    \"embeds\": [
                      {
                        \"title\": \"$title\",
                        \"description\": \"$description\",
                        \"color\": $color,
                        \"fields\": [
                          {
                            \"name\": \"📝 작업 제목\",
                            \"value\": $SAFE_PR_TITLE,
                            \"inline\": false
                          },
                          {
                            \"name\": \"🔗 디버그 URL\",
                            \"value\": \"[Actions 로그 보기](${ACTIONS_URL})\\n\\n\",
                            \"inline\": false
                          }
                        ]
                      }
                    ]
                  }" \
              ${{ secrets.DISCORD_WEBHOOK_URL }}
          }

          if [ "${{ job.status }}" = "success" ]; then
            send_discord_notification "success"
          else
            send_discord_notification "failure"
          fi
