name: Deploy Vue to AWS

on:
  push:
    branches:
      - "master"
    types:
      - opened
      - reopend
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. 환경 변수 설정 및 빌드
      - name: Build Vue application
        env:
          VITE_APP_TITLE: ${{ secrets.VITE_APP_TITLE }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_LAMBDA_API_BASE_URL: ${{ secrets.VITE_LAMBDA_API_BASE_URL }}
          VITE_FAST_API_BASE_URL: ${{ secrets.VITE_FAST_API_BASE_URL }}
          VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}
        run: |
          npm install
          npm run build

      # 4. AWS S3에 배포
      - name: Deploy to S3
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync to S3
        run: |
          aws s3 sync ./dist s3://my-vue-app-bucket --delete

      # 5. CloudFront 캐시 무효화
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
